Feature/issue 3 implement stroy crud api
bsse1009/blogger-api-restful pull request #5
Opened 2023-03-16 07:35 UTC by bsse1009

**Story** 
{
-  id(pk) -->uuid
- title
- description
- created_at
- updated_at
- authorId (fk)
}

**crud opertion**

- user 1 , user 2 -> authorized
- user 1 , user 2 -> create  story
- user 1 story -> user 1 read, update, delete story
- user 1 story -> user 2, unauthorized -> only read story

2023-03-16 08:09 UTC, edge555 commented on server/controllers/stories.controller.js
> +    }
in both cases, if the status is 4xx series or other you are executing the same line 'res.status(status).send(message)'

2023-03-18 06:01 UTC, rafaelragib requested changes

2023-03-18 16:19 UTC, bsse1009 commented on server/controllers/stories.controller.js
> +    const {title, description} = await req.body;
No vaiya.
In that case, title and description should be undefined.

2023-03-24 03:55 UTC, rafaelragib approved these changes
I am approving the PR. Fix the typo issue then merge it

2023-03-24 03:55 UTC, rafaelragib commented on server/controllers/stories.controller.js
> +  async getStroiesByAuthor(req, res) {
```suggestion
  async getStoriesByAuthor(req, res) {
```

2023-03-28 06:16 UTC, merged